on: 
  workflow_dispatch:
    inputs:
      tag:
        required: true

# on:
#   release:
#     types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      workdir: ./java-package
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        # if: ${{ startsWith(github.ref, 'java-') }}
        if: ${{ startsWith(github.event.inputs.tag, 'java-') }}
        with:
          java-version: 11
      - uses: actions/cache@v2
        # if: ${{ startsWith(github.ref, 'java-') }}
        if: ${{ startsWith(github.event.inputs.tag, 'java-') }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      # - run: mvn org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${GITHUB_REF##java-}
      - run: mvn org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${REF##java-}
        env:
          REF: ${{ github.event.inputs.tag }}
        # if: ${{ startsWith(github.ref, 'java-') }}
        if: ${{ startsWith(github.event.inputs.tag, 'java-') }}
        working-directory: ${{env.workdir}}
      - run: mvn -Prelease deploy
        # if: ${{ startsWith(github.ref, 'java-') }}
        if: ${{ startsWith(github.event.inputs.tag, 'java-') }}
        working-directory: ${{env.workdir}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
          workdir: ./java-package