on: workflow_dispatch
# on:
#   release:
#     types: [ created ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        if: ${{ startsWith(github.ref, 'java-') }}
        with:
          java-version: 11
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_CENTRAL_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - uses: actions/cache@v2
        if: ${{ startsWith(github.ref, 'java-') }}
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn org.codehaus.mojo:versions-maven-plugin:2.7:set -DnewVersion=${GITHUB_REF##java-}
        if: ${{ startsWith(github.ref, 'java-') }}
      - run: mvn -Prelease,maven deploy
        if: ${{ startsWith(github.ref, 'java-') }}
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USER }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
